// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8U5dinOagKYLERTB2oDqTbeoCidq-Noc',
    appId: '1:635130919542:android:fcc0df5c7a45114f81fd57',
    messagingSenderId: '635130919542',
    projectId: 'ajeer-e7ed6',
    storageBucket: 'ajeer-e7ed6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmCgbIlfdg-WjB96uTk7NWO3DLGKCvTEk',
    appId: '1:635130919542:ios:30dd74e9fd475a2f81fd57',
    messagingSenderId: '635130919542',
    projectId: 'ajeer-e7ed6',
    storageBucket: 'ajeer-e7ed6.firebasestorage.app',
    iosBundleId: 'com.ajeer.app.ajeer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXErkj4XeRpT7KdgUvaSNHZeIrJcKyMHM',
    appId: '1:635130919542:web:beb00d432f812f6a81fd57',
    messagingSenderId: '635130919542',
    projectId: 'ajeer-e7ed6',
    authDomain: 'ajeer-e7ed6.firebaseapp.com',
    storageBucket: 'ajeer-e7ed6.firebasestorage.app',
    measurementId: 'G-HGK7X6JS9X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmCgbIlfdg-WjB96uTk7NWO3DLGKCvTEk',
    appId: '1:635130919542:ios:30dd74e9fd475a2f81fd57',
    messagingSenderId: '635130919542',
    projectId: 'ajeer-e7ed6',
    storageBucket: 'ajeer-e7ed6.firebasestorage.app',
    iosBundleId: 'com.ajeer.app.ajeer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXErkj4XeRpT7KdgUvaSNHZeIrJcKyMHM',
    appId: '1:635130919542:web:7b79af2af28353f181fd57',
    messagingSenderId: '635130919542',
    projectId: 'ajeer-e7ed6',
    authDomain: 'ajeer-e7ed6.firebaseapp.com',
    storageBucket: 'ajeer-e7ed6.firebasestorage.app',
    measurementId: 'G-SE59M9E9XP',
  );

}